# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'erroreIscrizione.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_erroreiscrizione(object):
    def setupUi(self, erroreiscrizione):
        erroreiscrizione.setObjectName("Dialog")
        erroreiscrizione.resize(400, 93)
        self.buttonBox = QtWidgets.QDialogButtonBox(erroreiscrizione)
        self.buttonBox.setGeometry(QtCore.QRect(20, 50, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(erroreiscrizione)
        self.label.setGeometry(QtCore.QRect(30, 20, 341, 20))
        self.label.setObjectName("label")

        self.retranslateUi(erroreiscrizione)
        self.buttonBox.accepted.connect(erroreiscrizione.accept) # type: ignore
        self.buttonBox.rejected.connect(erroreiscrizione.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(erroreiscrizione)

    def retranslateUi(self, erroreiscrizione):
        _translate = QtCore.QCoreApplication.translate
        erroreiscrizione.setWindowTitle(_translate("erroreiscrizione", "Dialog"))
        self.label.setText(_translate("erroreiscrizione", "hai lasciato un campo vuoto, devono essere tutti pieni!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    erroreiscrizione = QtWidgets.QDialog()
    ui = Ui_erroreiscrizione()
    ui.setupUi(erroreiscrizione)
    erroreiscrizione.show()
    sys.exit(app.exec_())