# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestionepartite.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Implementazione.Generali.Partita import Partita
from Implementazione.Gestione.GestoreUtenti import GestoreUtenti
from PyQt5.QtWidgets import QTableWidgetItem

from Implementazione.Viste.modificapartita import Ui_modificapartita


class Ui_gestionepartite(object):

    def modificaPartita(self):
        self.tabellapartite.currentRow()
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_modificapartita()
        self.ui.setupUi(self.window,self.tabellapartite.currentRow())
        self.window.show()
        if(self.ui.modificaPartita()):self.window.hide()


    def aggiungiPartita(self):
        if(GestoreUtenti.utenteConnesso.isAdmin==False):giocatoreuno=GestoreUtenti.utenteConnesso.nome
        else: giocatoreuno=self.giocatoreuno.text()
        giocatoredue=self.giocatoredue.text()
        punteggiouno=self.spinuno.value()
        punteggiodue=self.spindue.value()
        partita=Partita(giocatoreuno,punteggiouno,giocatoredue,punteggiodue)
        Ui_gestionepartite.prenotazione.aggiungiPartita(partita)
        print(Ui_gestionepartite.prenotazione.collectionPartite[0].getPunteggioGiocatoreUno())
        self.visualizzaPartite()

    def visualizzaPartite(self):
        self.tabellapartite.setRowCount(len(Ui_gestionepartite.prenotazione.collectionPartite))
        for i in range(len(Ui_gestionepartite.prenotazione.collectionPartite)):
            item = QTableWidgetItem(Ui_gestionepartite.prenotazione.collectionPartite[i].giocatoreuno)
            self.tabellapartite.setItem(i, 0, item)
            item = QTableWidgetItem(str(Ui_gestionepartite.prenotazione.collectionPartite[i].punteggiouno))
            self.tabellapartite.setItem(i, 1, item)
            item = QTableWidgetItem(Ui_gestionepartite.prenotazione.collectionPartite[i].giocatoredue)
            self.tabellapartite.setItem(i, 2, item)
            item = QTableWidgetItem(str(Ui_gestionepartite.prenotazione.collectionPartite[i].punteggiodue))
            self.tabellapartite.setItem(i, 3, item)
        self.statistiche.setText(Ui_gestionepartite.prenotazione.getStatistiche())

    def setupUi(self, gestionepartite,prenotazione):
        Ui_gestionepartite.prenotazione=prenotazione
        gestionepartite.setObjectName("gestionepartite")
        gestionepartite.resize(500, 320)
        self.giocatoreuno = QtWidgets.QLineEdit(gestionepartite)
        self.giocatoreuno.setGeometry(QtCore.QRect(40, 40, 113, 21))
        self.giocatoreuno.setObjectName("giocatoreuno")

        if GestoreUtenti.utenteConnesso.isAdmin==False:
            self.giocatoreuno.setEnabled(False)
            self.giocatoreuno.setText(GestoreUtenti.utenteConnesso.nome)
        self.giocatoredue = QtWidgets.QLineEdit(gestionepartite)
        self.giocatoredue.setGeometry(QtCore.QRect(190, 40, 113, 21))
        self.giocatoredue.setObjectName("giocatoredue")
        self.spinuno = QtWidgets.QSpinBox(gestionepartite)
        self.spinuno.setGeometry(QtCore.QRect(50, 80, 48, 24))
        self.spinuno.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinuno.setMaximum(3)
        self.spinuno.setObjectName("spinuno")
        self.spindue = QtWidgets.QSpinBox(gestionepartite)
        self.spindue.setGeometry(QtCore.QRect(220, 80, 48, 24))
        self.spindue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spindue.setMaximum(3)
        self.spindue.setObjectName("spin2")
        self.labeluno = QtWidgets.QLabel(gestionepartite)
        self.labeluno.setGeometry(QtCore.QRect(40, 20, 71, 16))
        self.labeluno.setObjectName("labeluno")
        self.labeldue = QtWidgets.QLabel(gestionepartite)
        self.labeldue.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.labeldue.setObjectName("labeldue")
        self.tabellapartite = QtWidgets.QTableWidget(gestionepartite)
        self.tabellapartite.setGeometry(QtCore.QRect(10, 180, 461, 121))
        self.tabellapartite.setObjectName("tabellapartite")
        self.tabellapartite.setColumnCount(4)
        self.tabellapartite.setRowCount(0)
        self.tabellapartite.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tabellapartite.setHorizontalHeaderLabels(["Giocatore 1","Punteggio","Giocatore 2","Punteggio"])
        self.tabellapartite.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.labeltre = QtWidgets.QLabel(gestionepartite)
        self.labeltre.setGeometry(QtCore.QRect(10, 160, 141, 16))
        self.labeltre.setObjectName("labeltre")
        self.statistiche = QtWidgets.QLineEdit(gestionepartite)
        self.statistiche.setGeometry(QtCore.QRect(250, 150, 113, 21))
        self.statistiche.setObjectName("statistiche")
        self.labelquattro = QtWidgets.QLabel(gestionepartite)
        self.labelquattro.setGeometry(QtCore.QRect(250, 130, 111, 16))
        self.labelquattro.setObjectName("labelquattro")
        self.aggiungipartita = QtWidgets.QPushButton(gestionepartite)
        self.aggiungipartita.setGeometry(QtCore.QRect(30, 120, 113, 32))
        self.aggiungipartita.setObjectName("aggiungipartita")

        #visualizza subito le partite fatte quel giorno dall'utente
        self.visualizzaPartite()

        self.aggiungipartita.clicked.connect(self.aggiungiPartita)
        self.tabellapartite.doubleClicked.connect(self.modificaPartita)

        self.retranslateUi(gestionepartite)
        QtCore.QMetaObject.connectSlotsByName(gestionepartite)

    def retranslateUi(self, gestionepartite):
        _translate = QtCore.QCoreApplication.translate
        gestionepartite.setWindowTitle(_translate("gestionepartite", "Form"))
        self.labeluno.setText(_translate("gestionepartite", "Giocatore1"))
        self.labeldue.setText(_translate("gestionepartite", "Giocatore2"))
        self.labeltre.setText(_translate("gestionepartite", "Partite di:"))
        self.labelquattro.setText(_translate("gestionepartite", "Tendenza vittorie"))
        self.aggiungipartita.setText(_translate("gestionepartite", "Aggiungi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gestionepartite = QtWidgets.QWidget()
    ui = Ui_gestionepartite()
    ui.setupUi(gestionepartite)
    gestionepartite.show()
    sys.exit(app.exec_())
