# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestione_organizzazione.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Implementazione.Viste.visualizzazione_liste import Ui_visualizzazioneliste


class Ui_gestioneOrganizzazione(object):

    def visualizzaListaUtenti(self):
        self.windows_visualizza = QtWidgets.QDialog()
        self.ui_visualizza = Ui_visualizzazioneliste()
        self.ui_visualizza.setupUi(self.windows_visualizza)
        self.windows_visualizza.show()

    def setupUi(self, gestioneOrganizzazione):
        gestioneOrganizzazione.setObjectName("gestioneOrganizzazione")
        gestioneOrganizzazione.resize(400, 300)
        self.listautenti = QtWidgets.QPushButton(gestioneOrganizzazione)
        self.listautenti.setGeometry(QtCore.QRect(110, 30, 171, 32))
        self.listautenti.setObjectName("pushButton")
        self.listasoci = QtWidgets.QPushButton(gestioneOrganizzazione)
        self.listasoci.setGeometry(QtCore.QRect(110, 60, 171, 32))
        self.listasoci.setObjectName("pushButton_2")

        #azioni dei pulsanti
        self.listautenti.clicked.connect(self.visualizzaListaUtenti)

        self.retranslateUi(gestioneOrganizzazione)
        QtCore.QMetaObject.connectSlotsByName(gestioneOrganizzazione)

    def retranslateUi(self, gestioneOrganizzazione):
        _translate = QtCore.QCoreApplication.translate
        gestioneOrganizzazione.setWindowTitle(_translate("gestioneOrganizzazione", "Form"))
        self.listautenti.setText(_translate("gestioneOrganizzazione", "Visualizza Lista Utenti"))
        self.listasoci.setText(_translate("gestioneOrganizzazione", "Visualizza Lista Soci"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gestioneOrganizzazione = QtWidgets.QWidget()
    ui = Ui_gestioneOrganizzazione()
    ui.setupUi(gestioneOrganizzazione)
    gestioneOrganizzazione.show()
    sys.exit(app.exec_())
