# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestionebackup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Implementazione.Gestione.GestoreBackup import GestoreBackup


class Ui_gestionebackup(object):

    def saveBackup(self):
        GestoreBackup.salvaDati()

    def loadBackup(self):
        GestoreBackup.caricaDati()

    def setupUi(self, gestionebackup):
        gestionebackup.setObjectName("gestionebackup")
        gestionebackup.resize(400, 146)
        self.buttonBox = QtWidgets.QDialogButtonBox(gestionebackup)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.save = QtWidgets.QPushButton(gestionebackup)
        self.save.setGeometry(QtCore.QRect(70, 20, 113, 32))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(gestionebackup)
        self.load.setGeometry(QtCore.QRect(70, 70, 113, 32))
        self.load.setObjectName("load")

        self.retranslateUi(gestionebackup)
        self.buttonBox.accepted.connect(gestionebackup.accept) # type: ignore
        self.buttonBox.rejected.connect(gestionebackup.reject) # type: ignore
        self.save.clicked.connect(self.saveBackup)
        self.load.clicked.connect(self.loadBackup)
        QtCore.QMetaObject.connectSlotsByName(gestionebackup)

    def retranslateUi(self, gestionebackup):
        _translate = QtCore.QCoreApplication.translate
        gestionebackup.setWindowTitle(_translate("gestionebackup", "Dialog"))
        self.save.setText(_translate("gestionebackup", "Salva backup"))
        self.load.setText(_translate("gestionebackup", "Carica backup"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gestionebackup = QtWidgets.QDialog()
    ui = Ui_gestionebackup()
    ui.setupUi(gestionebackup)
    gestionebackup.show()
    sys.exit(app.exec_())
