# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pickle

from PyQt5 import QtCore, QtGui, QtWidgets

from Implementazione.Viste.gestionebackup import Ui_gestionebackup
from Implementazione.Viste.login import Login
from Implementazione.Viste.registrazione_socio import Ui_registrazionesocio
from Implementazione.Gestione.GestoreUtenti import GestoreUtenti
from Implementazione.Viste.gestione_organizzazione import Ui_gestioneOrganizzazione
from Implementazione.Viste.prenotazioni import Ui_prenotazioni
from Implementazione.Gestione.GestoreBackup import GestoreBackup

class Ui_Form(object):

    def gestioneBackup(self):
        self.window_conferma = QtWidgets.QDialog()
        self.ui_conferma = Ui_gestionebackup()
        self.ui_conferma.setupUi(self.window_conferma)
        self.window_conferma.show()

    def gestioneUtente(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Login()
        self.ui.setupUi(self.window)
        self.window.show()

    def gestioneTesseramento(self):
        if GestoreUtenti.loginEffettuato == True:
            self.window=QtWidgets.QWidget()
            self.ui=Ui_registrazionesocio()
            self.ui.setupUi(self.window)
            self.window.show()

    def gestioneOrganizzazione(self):
        if (GestoreUtenti.loginEffettuato == True
                and (GestoreUtenti.utenteConnesso.isAdmin == True or
                    GestoreUtenti.utenteConnesso.isCustode==True)):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_gestioneOrganizzazione()
            self.ui.setupUi(self.window)
            self.window.show()

    def gestionePrenotazioni(self):
        if (GestoreUtenti.loginEffettuato == True):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_prenotazioni()
            self.ui.setupUi(self.window)
            self.window.show()


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 405)
        self.gestioneprenotazioni = QtWidgets.QPushButton(Form)
        self.gestioneprenotazioni.setGeometry(QtCore.QRect(20, 30, 171, 111))
        self.gestioneprenotazioni.setObjectName("gestionePrenotazioni")
        self.gestioneutente = QtWidgets.QPushButton(Form)
        self.gestioneutente.setGeometry(QtCore.QRect(210, 30, 171, 111))
        self.gestioneutente.setObjectName("gestioneUtente")
        self.gestionetesseramento = QtWidgets.QPushButton(Form)
        self.gestionetesseramento.setGeometry(QtCore.QRect(20, 160, 171, 111))
        self.gestionetesseramento.setObjectName("gestioneTesseramento")
        self.gestionetorneo = QtWidgets.QPushButton(Form)
        self.gestionetorneo.setGeometry(QtCore.QRect(210, 160, 171, 111))
        self.gestionetorneo.setObjectName("gestioneBackup")
        self.gestioneorganizzazione = QtWidgets.QPushButton(Form)
        self.gestioneorganizzazione.setGeometry(QtCore.QRect(50, 290, 301, 111))
        self.gestioneorganizzazione.setObjectName("gestioneOrganizzazione")




        #azioni dei pulsanti
        self.gestioneutente.clicked.connect(self.gestioneUtente)
        self.gestionetesseramento.clicked.connect(self.gestioneTesseramento)
        self.gestioneorganizzazione.clicked.connect(self.gestioneOrganizzazione)
        self.gestioneprenotazioni.clicked.connect(self.gestionePrenotazioni)
        self.gestionetorneo.clicked.connect(self.gestioneBackup)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gestioneprenotazioni.setText(_translate("Form", "Gestione Prenotazioni"))
        self.gestioneutente.setText(_translate("Form", "Gestione Utente"))
        self.gestionetesseramento.setText(_translate("Form", "Gestione Tesseramento"))
        self.gestionetorneo.setText(_translate("Form", "Gestione Backup"))
        self.gestioneorganizzazione.setText(_translate("Form", "Gestione Organizzazione"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
