# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login(object):
    def autenticazione(self):
        username=self.logIn.text()
        pwd=self.password.text()
        if(username=="ivan" ):
            self.accessoEffettuato

    def accessoEffetuato(self):

        print("ciao")

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(491, 356)
        self.logIn = QtWidgets.QPushButton(Form)
        self.logIn.setGeometry(QtCore.QRect(120, 140, 113, 32))
        self.logIn.setObjectName("logIn")
        self.iscriviti = QtWidgets.QPushButton(Form)
        self.iscriviti.setGeometry(QtCore.QRect(280, 140, 113, 32))
        self.iscriviti.setObjectName("iscriviti")
        self.nomeUtente = QtWidgets.QLineEdit(Form)
        self.nomeUtente.setGeometry(QtCore.QRect(170, 70, 171, 21))
        self.nomeUtente.setObjectName("nomeUtente")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(170, 100, 171, 21))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 70, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 60, 16))
        self.label_2.setObjectName("label_2")
        self.logIn.clicked.connect(self.accessoEffetuato)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logIn.setText(_translate("Form", "Login"))
        self.iscriviti.setText(_translate("Form", "Iscriviti"))
        self.label.setText(_translate("Form", "Nome utente"))
        self.label_2.setText(_translate("Form", "Password"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Login()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
