# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Implementazione.Viste.registrazione_utente import UI_Iscrizione
from Implementazione.Gestione.GestoreUtente import GestoreUtente
from Implementazione.Generali.Utente import Utente
from Implementazione.Viste.logineffettuato import Ui_logineffettuato


class Login(object):

    def autenticazione(self):
        nomeUtente=self.nomeUtente.text()
        pwd=self.password.text()
        for x in GestoreUtente.collectionUtenti:
            if x.nomeUtente == nomeUtente and x.password == pwd:
                GestoreUtente.setLoginEffettuato()
                GestoreUtente.setUtenteConnesso(x)
                self.loginPopup()


    def loginPopup(self):
        self.window_conferma = QtWidgets.QDialog()
        self.ui_conferma = Ui_logineffettuato()
        self.ui_conferma.setupUi(self.window_conferma)
        self.window_conferma.show()

    def logoutPopup(self):
        if GestoreUtente.loginEffettuato==True:
            GestoreUtente.setLogoutEffettuato()
            self.window_conferma = QtWidgets.QDialog()
            self.ui_conferma = Ui_logineffettuato()
            self.ui_conferma.setupUi(self.window_conferma)
            self.window_conferma.show()


    def iscrizione(self):
        self.window_iscrizione = QtWidgets.QMainWindow()
        self.ui_iscrizione = UI_Iscrizione()
        self.ui_iscrizione.setupUi(self.window_iscrizione,0)
        self.window_iscrizione.show()

    def modificaDati(self):
        if (GestoreUtente.loginEffettuato):
            self.window_iscrizione = QtWidgets.QMainWindow()
            self.ui_iscrizione = UI_Iscrizione()
            self.ui_iscrizione.setupUi(self.window_iscrizione,0)
            self.window_iscrizione.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(467, 269)
        self.logIn = QtWidgets.QPushButton(Form)
        self.logIn.setGeometry(QtCore.QRect(120, 140, 113, 32))
        self.logIn.setObjectName("logIn")
        self.logOut = QtWidgets.QPushButton(Form)
        self.logOut.setGeometry(QtCore.QRect(120, 210, 113, 32))
        self.logOut.setObjectName("logOut")
        self.modifica = QtWidgets.QPushButton(Form)
        self.modifica.setGeometry(QtCore.QRect(280, 210, 113, 32))
        self.modifica.setObjectName("modifica")
        self.iscriviti = QtWidgets.QPushButton(Form)
        self.iscriviti.setGeometry(QtCore.QRect(280, 140, 113, 32))
        self.iscriviti.setObjectName("iscriviti")
        self.nomeUtente = QtWidgets.QLineEdit(Form)
        self.nomeUtente.setGeometry(QtCore.QRect(170, 70, 171, 21))
        self.nomeUtente.setObjectName("nomeUtente")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(170, 100, 171, 21))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 70, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 60, 16))
        self.label_2.setObjectName("label_2")

        #azione quando i pulsanti si cliccano
        self.logIn.clicked.connect(self.autenticazione)
        self.iscriviti.clicked.connect(self.iscrizione)
        self.modifica.clicked.connect(self.modificaDati)
        self.logOut.clicked.connect(self.logoutPopup)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logIn.setText(_translate("Form", "Login"))
        self.iscriviti.setText(_translate("Form", "Iscriviti"))
        self.label.setText(_translate("Form", "Nome utente"))
        self.label_2.setText(_translate("Form", "Password"))
        self.modifica.setText(_translate("Form", "Modifica"))
        self.logOut.setText(_translate("Form", "Logout"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Login()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
