# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificaIscrizione.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modificaiscrizione(object):
    def setupUi(self, modificaiscrizione):
        modificaiscrizione.setObjectName("Dialog")
        modificaiscrizione.resize(400, 93)
        self.buttonBox = QtWidgets.QDialogButtonBox(modificaiscrizione)
        self.buttonBox.setGeometry(QtCore.QRect(20, 50, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(modificaiscrizione)
        self.label.setGeometry(QtCore.QRect(30, 20, 341, 20))
        self.label.setObjectName("label")

        self.retranslateUi(modificaiscrizione)
        self.buttonBox.accepted.connect(modificaiscrizione.accept) # type: ignore
        self.buttonBox.rejected.connect(modificaiscrizione.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(modificaiscrizione)

    def retranslateUi(self, modificaiscrizione):
        _translate = QtCore.QCoreApplication.translate
        modificaiscrizione.setWindowTitle(_translate("modificaiscrizione", "Dialog"))
        self.label.setText(_translate("modificaiscrizione", "Modifica effettuata"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modificaiscrizione = QtWidgets.QDialog()
    ui = Ui_modificaiscrizione()
    ui.setupUi(modificaiscrizione)
    modificaiscrizione.show()
    sys.exit(app.exec_())
