# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificapartita.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Implementazione.Generali.Partita import Partita
from Implementazione.Gestione.GestoreUtenti import GestoreUtenti


class Ui_modificapartita(object):



    def modificaPartita(self):
        giocatoreuno = self.giocatoreuno.text()
        giocatoredue = self.giocatoredue.text()
        punteggiouno = self.spinuno.value()
        punteggiodue = self.spindue.value()
        partita = Partita(giocatoreuno, punteggiouno, giocatoredue, punteggiodue)
        from Implementazione.Viste.gestionepartite import Ui_gestionepartite
        Ui_gestionepartite.prenotazione.modificaPartita(Ui_modificapartita.rigapartita,partita)


    def setupUi(self, gestionepartite,rigapartita):
        gestionepartite.setObjectName("modificapartita")
        gestionepartite.resize(326, 189)
        self.buttonBox = QtWidgets.QDialogButtonBox(gestionepartite)
        self.buttonBox.setGeometry(QtCore.QRect(70, 130, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.giocatoreuno = QtWidgets.QLineEdit(gestionepartite)
        self.giocatoreuno.setGeometry(QtCore.QRect(30, 50, 113, 21))
        self.giocatoreuno.setObjectName("giocatoreuno")
        self.labeluno = QtWidgets.QLabel(gestionepartite)
        self.labeluno.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.labeluno.setObjectName("labeluno")
        self.spindue = QtWidgets.QSpinBox(gestionepartite)
        self.spindue.setGeometry(QtCore.QRect(210, 90, 48, 24))
        self.spindue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spindue.setMaximum(3)
        self.spindue.setObjectName("spin2")
        self.spinuno = QtWidgets.QSpinBox(gestionepartite)
        self.spinuno.setGeometry(QtCore.QRect(40, 90, 48, 24))
        self.spinuno.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinuno.setMaximum(3)
        self.spinuno.setObjectName("spinuno")
        self.labeldue = QtWidgets.QLabel(gestionepartite)
        self.labeldue.setGeometry(QtCore.QRect(180, 30, 71, 16))
        self.labeldue.setObjectName("labeldue")
        self.giocatoredue = QtWidgets.QLineEdit(gestionepartite)
        self.giocatoredue.setGeometry(QtCore.QRect(180, 50, 113, 21))
        self.giocatoredue.setObjectName("giocatoredue")

        self.retranslateUi(gestionepartite)
        self.buttonBox.accepted.connect(self.modificaPartita)
        self.buttonBox.accepted.connect(gestionepartite.accept)  # type: ignore
        self.buttonBox.rejected.connect(gestionepartite.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(gestionepartite)
        from Implementazione.Viste.gestionepartite import Ui_gestionepartite
        if (GestoreUtenti.utenteConnesso.isAdmin==False):
            self.giocatoreuno.setText(GestoreUtenti.utenteConnesso.nome)
            self.giocatoreuno.setEnabled(False)
        self.giocatoredue.setText(Ui_gestionepartite.prenotazione.collectionPartite[rigapartita].giocatoredue)
        self.spinuno.setValue(Ui_gestionepartite.prenotazione.collectionPartite[rigapartita].punteggiouno)
        self.spindue.setValue(Ui_gestionepartite.prenotazione.collectionPartite[rigapartita].punteggiodue)
        Ui_modificapartita.rigapartita=rigapartita




    def retranslateUi(self, modificapartita):
        _translate = QtCore.QCoreApplication.translate
        modificapartita.setWindowTitle(_translate("modificapartita", "Dialog"))
        self.labeluno.setText(_translate("modificapartita", "Giocatore1"))
        self.labeldue.setText(_translate("modificapartita", "Giocatore2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gestionepartite = QtWidgets.QDialog()
    ui = Ui_modificapartita()
    ui.setupUi(gestionepartite)
    gestionepartite.show()
    sys.exit(app.exec_())

