# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificapartita.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Implementazione.Generali.Partita import Partita


class Ui_modificapartita(object):



    def modificaPartita(self):
        giocatoreuno = self.giocatoreuno.text()
        giocatoredue = self.giocatoredue.text()
        punteggiouno = self.spinuno.value()
        punteggiodue = self.spindue.value()
        partita = Partita(giocatoreuno, punteggiouno, giocatoredue, punteggiodue)
        from Implementazione.Viste.gestionepartite import Ui_gestionepartite
        Ui_gestionepartite.prenotazione.modificaPartita(Ui_modificapartita.rigapartita,partita)


    def setupUi(self, gestionepartite,rigapartita):
        gestionepartite.setObjectName("gestionepartite")
        gestionepartite.resize(316, 162)
        self.giocatoreuno = QtWidgets.QLineEdit(gestionepartite)
        self.giocatoreuno.setGeometry(QtCore.QRect(40, 40, 113, 21))
        self.giocatoreuno.setObjectName("giocatoreuno")
        self.giocatoredue = QtWidgets.QLineEdit(gestionepartite)
        self.giocatoredue.setGeometry(QtCore.QRect(190, 40, 113, 21))
        self.giocatoredue.setObjectName("giocatoredue")
        self.spinuno = QtWidgets.QSpinBox(gestionepartite)
        self.spinuno.setGeometry(QtCore.QRect(50, 80, 48, 24))
        self.spinuno.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinuno.setMaximum(3)
        self.spinuno.setObjectName("spinuno")
        self.spindue = QtWidgets.QSpinBox(gestionepartite)
        self.spindue.setGeometry(QtCore.QRect(220, 80, 48, 24))
        self.spindue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spindue.setMaximum(3)
        self.spindue.setObjectName("spin2")
        self.labeluno = QtWidgets.QLabel(gestionepartite)
        self.labeluno.setGeometry(QtCore.QRect(40, 20, 71, 16))
        self.labeluno.setObjectName("labeluno")
        self.labeldue = QtWidgets.QLabel(gestionepartite)
        self.labeldue.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.labeldue.setObjectName("labeldue")
        self.aggiungipartita = QtWidgets.QPushButton(gestionepartite)
        self.aggiungipartita.setGeometry(QtCore.QRect(110, 120, 113, 32))
        self.aggiungipartita.setObjectName("aggiungipartita")
        from Implementazione.Viste.gestionepartite import Ui_gestionepartite
        self.giocatoreuno.setText(Ui_gestionepartite.prenotazione.collectionPartite[rigapartita].giocatoreuno)
        self.giocatoredue.setText(Ui_gestionepartite.prenotazione.collectionPartite[rigapartita].giocatoredue)
        self.spinuno.setValue(Ui_gestionepartite.prenotazione.collectionPartite[rigapartita].punteggiouno)
        self.spindue.setValue(Ui_gestionepartite.prenotazione.collectionPartite[rigapartita].punteggiodue)
        Ui_modificapartita.rigapartita=rigapartita
        self.aggiungipartita.clicked.connect(self.modificaPartita)

        self.retranslateUi(gestionepartite)
        QtCore.QMetaObject.connectSlotsByName(gestionepartite)

    def retranslateUi(self, gestionepartite):
        _translate = QtCore.QCoreApplication.translate
        gestionepartite.setWindowTitle(_translate("gestionepartite", "Form"))
        self.labeluno.setText(_translate("gestionepartite", "Giocatore1"))
        self.labeldue.setText(_translate("gestionepartite", "Giocatore2"))
        self.aggiungipartita.setText(_translate("gestionepartite", "Aggiungi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gestionepartite = QtWidgets.QWidget()
    ui = Ui_modificapartita()
    ui.setupUi(gestionepartite)
    gestionepartite.show()
    sys.exit(app.exec_())
