# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prenotazioni.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

from Implementazione.Gestione.GestoreUtenti import GestoreUtenti
from Implementazione.Gestione.GestorePrenotazioni import GestorePrenotazioni
from Implementazione.Viste.conferma_prenotazione import Ui_conferma_prenotazione
from Implementazione.Viste.errore_prenotazione import Ui_erroreprenotazione
from Implementazione.Viste.visualizzazione_liste import Ui_visualizzazioneliste


class Ui_prenotazioni(object):

    def inserisciPrenotazione(self):
        data = str(self.calendario.selectedDate())\
            .replace('PyQt5.QtCore.QDate','')\
            .replace('(','')\
            .replace(')','')
        riga=self.tabellaprenotazioni.currentRow()
        colonna=self.tabellaprenotazioni.currentColumn()
        if(self.tabellaprenotazioni.currentItem()==None and GestoreUtenti.utenteConnesso.isAdmin==True):
            self.visualizzasoci = False
            self.windows_visualizza = QtWidgets.QDialog()
            self.ui_visualizza = Ui_visualizzazioneliste()
            self.ui_visualizza.setupUi(self.windows_visualizza, False)
            self.windows_visualizza.show()
            if (self.windows_visualizza.exec() == 1):
                print(self.ui_visualizza.getUtenteSelezionato())
            self.visualizzaPrenotazioni()
        elif (self.tabellaprenotazioni.currentItem() == None):
            self.window_conferma = QtWidgets.QDialog()
            self.ui_conferma = Ui_conferma_prenotazione()
            self.ui_conferma.setupUi(self.window_conferma)
            if (self.window_conferma.exec() == 1):
                GestorePrenotazioni.inserisciPrenotazione(data, riga, colonna)
            else:
                pass
            self.visualizzaPrenotazioni()
        else:
            self.window_conferma = QtWidgets.QDialog()
            self.ui_conferma = Ui_erroreprenotazione()
            self.ui_conferma.setupUi(self.window_conferma)
            self.window_conferma.show()







    def visualizzaPrenotazioni(self):

        self.tabellaprenotazioni.clearContents()
        data = str(self.calendario.selectedDate())\
            .replace('PyQt5.QtCore.QDate','')\
            .replace('(','')\
            .replace(')','')
        colonna=0
        for i in range(len(GestorePrenotazioni.collectionPrenotazioni)):
            if GestorePrenotazioni.collectionPrenotazioni[i].data == str(data):
                if GestorePrenotazioni.collectionPrenotazioni[i].campo.tipoCampo=="Terra Rossa Coperto":
                    colonna=0
                if GestorePrenotazioni.collectionPrenotazioni[i].campo.tipoCampo=="Terra Rossa":
                    colonna=1
                if GestorePrenotazioni.collectionPrenotazioni[i].campo.tipoCampo=="Erba sintetica":
                    colonna=2
                if GestorePrenotazioni.collectionPrenotazioni[i].campo.tipoCampo=="Paddle":
                    colonna=3
                for j in range (8,23):
                    if j<10: oraInizio="0"+str(j)+":00"
                    else: oraInizio=str(j)+":00"
                    if GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == oraInizio:
                        item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                        self.tabellaprenotazioni.setItem(j-8, colonna, item)
                '''elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "09:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(1, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "10:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(2, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "11:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(3, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "12:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(4, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "13:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(5, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "14:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(6, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "15:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(7, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "16:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(8, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "17:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(9, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "18:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(10, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "19:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(11, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "20:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(12, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "21:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(13, colonna, item)
                elif GestorePrenotazioni.collectionPrenotazioni[i].oraInizio == "22:00":
                    item = QTableWidgetItem(GestorePrenotazioni.collectionPrenotazioni[i].utente.nome)
                    self.tabellaprenotazioni.setItem(14, colonna, item)'''




    def setupUi(self, prenotazioni):
        prenotazioni.setObjectName("prenotazioni")
        prenotazioni.resize(906, 368)
        self.orari=["8-9","9-10","10-11","11-12","12-13","13-14",
                    "14-15","15-16","16-17","17-18","18-19","19-20",
                    "20-21","21-22","22-23"]
        self.calendario = QtWidgets.QCalendarWidget(prenotazioni)
        self.calendario.setGeometry(QtCore.QRect(20, 10, 304, 173))
        self.calendario.setMinimumDate(QtCore.QDate(2022, 7, 4))
        self.calendario.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.calendario.setFirstDayOfWeek(QtCore.Qt.Sunday)
        self.calendario.setGridVisible(True)
        self.calendario.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendario.setNavigationBarVisible(True)
        self.calendario.setObjectName("calendario")
        self.tabellaprenotazioni = QtWidgets.QTableWidget(prenotazioni)
        self.tabellaprenotazioni.setGeometry(QtCore.QRect(335, 10, 531, 331))
        self.tabellaprenotazioni.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tabellaprenotazioni.setRowCount(14)
        self.tabellaprenotazioni.setColumnCount(4)
        self.tabellaprenotazioni.setObjectName("tabellaprenotazioni")
        self.tabellaprenotazioni.horizontalHeader().setDefaultSectionSize(120)
        self.tabellaprenotazioni.verticalHeader().setDefaultSectionSize(20)
        self.tabellaprenotazioni.setHorizontalHeaderLabels(["Terra Rossa Coperto", "Terra Rossa", "Erba Sintetica", "Paddle"])
        self.tabellaprenotazioni.setVerticalHeaderLabels(self.orari)
        self.inserisciprenotazione = QtWidgets.QPushButton(prenotazioni)
        self.inserisciprenotazione.setGeometry(QtCore.QRect(210, 190, 113, 32))
        self.inserisciprenotazione.setObjectName("inserisciprenotazione")
        self.eliminaprenotazione = QtWidgets.QPushButton(prenotazioni)
        self.eliminaprenotazione.setGeometry(QtCore.QRect(210, 260, 113, 32))
        self.eliminaprenotazione.setObjectName("eliminaprenotazione")
        self.modificaprenotazione = QtWidgets.QPushButton(prenotazioni)
        self.modificaprenotazione.setGeometry(QtCore.QRect(210, 220, 113, 32))
        self.modificaprenotazione.setObjectName("modificaprenotazione")
        self.visualizzaPrenotazioni()
        self.calendario.clicked.connect(self.visualizzaPrenotazioni)
        self.inserisciprenotazione.clicked.connect(self.inserisciPrenotazione)
        self.retranslateUi(prenotazioni)
        QtCore.QMetaObject.connectSlotsByName(prenotazioni)

    def retranslateUi(self, prenotazioni):
        _translate = QtCore.QCoreApplication.translate
        prenotazioni.setWindowTitle(_translate("prenotazioni", "Form"))
        self.inserisciprenotazione.setText(_translate("prenotazioni", "Inserisci"))
        self.eliminaprenotazione.setText(_translate("prenotazioni", "Elimina"))
        self.modificaprenotazione.setText(_translate("prenotazioni", "Modifica"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    prenotazioni = QtWidgets.QWidget()
    ui = Ui_prenotazioni()
    ui.setupUi(prenotazioni)
    prenotazioni.show()
    sys.exit(app.exec_())
