# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrazione_utente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from Implementazione.Generali.Utente import Utente
from Implementazione.Gestione.GestoreUtente import GestoreUtente


class Iscrizione(object):
    def creaUtente(self):
        campoNome=self.nome.text()
        campoCognome=self.cognome.text()
        campoNomeUtente=self.nomeUtente.text()
        campoPassword=self.password.text()
        campoCellulare=self.password.text()
        campoDataNascita=self.cellulare.text()
        nuovoUtente=Utente(campoNome,campoCognome,campoDataNascita,campoCellulare,campoPassword,campoNomeUtente)
        GestoreUtente.inserisciUtente(nuovoUtente)
        GestoreUtente.visualizzaListaUtenti()


    def setupUi(self, Iscrizione):
        Iscrizione.setObjectName("Iscrizione")
        Iscrizione.resize(400, 300)
        self.label_3 = QtWidgets.QLabel(Iscrizione)
        self.label_3.setGeometry(QtCore.QRect(59, 90, 81, 20))
        self.label_3.setObjectName("label_3")
        self.cognome = QtWidgets.QLineEdit(Iscrizione)
        self.cognome.setGeometry(QtCore.QRect(150, 60, 141, 21))
        self.cognome.setObjectName("cognome")
        self.label = QtWidgets.QLabel(Iscrizione)
        self.label.setGeometry(QtCore.QRect(100, 30, 41, 16))
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(Iscrizione)
        self.password.setGeometry(QtCore.QRect(150, 120, 141, 21))
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(Iscrizione)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 60, 16))
        self.label_2.setObjectName("label_2")
        self.nomeUtente = QtWidgets.QLineEdit(Iscrizione)
        self.nomeUtente.setGeometry(QtCore.QRect(150, 90, 141, 21))
        self.nomeUtente.setObjectName("nomeUtente")
        self.nome = QtWidgets.QLineEdit(Iscrizione)
        self.nome.setGeometry(QtCore.QRect(150, 30, 141, 21))
        self.nome.setObjectName("nome")
        self.label_4 = QtWidgets.QLabel(Iscrizione)
        self.label_4.setGeometry(QtCore.QRect(80, 120, 60, 16))
        self.label_4.setObjectName("label_4")
        self.invia = QtWidgets.QPushButton(Iscrizione)
        self.invia.setGeometry(QtCore.QRect(150, 220, 113, 32))
        self.invia.setFlat(False)
        self.invia.setObjectName("invia")
        self.label_5 = QtWidgets.QLabel(Iscrizione)
        self.label_5.setGeometry(QtCore.QRect(80, 150, 60, 16))
        self.label_5.setObjectName("label_5")
        self.cellulare = QtWidgets.QLineEdit(Iscrizione)
        self.cellulare.setGeometry(QtCore.QRect(150, 150, 141, 21))
        self.cellulare.setObjectName("cellulare")

        #azioni dei pulsanti
        self.invia.clicked.connect(self.creaUtente)

        self.retranslateUi(Iscrizione)
        QtCore.QMetaObject.connectSlotsByName(Iscrizione)

    def retranslateUi(self, Iscrizione):
        _translate = QtCore.QCoreApplication.translate
        Iscrizione.setWindowTitle(_translate("Iscrizione", "Form"))
        self.label_3.setText(_translate("Iscrizione", "Nome Utente"))
        self.label.setText(_translate("Iscrizione", "Nome"))
        self.label_2.setText(_translate("Iscrizione", "Cognome"))
        self.label_4.setText(_translate("Iscrizione", "Password"))
        self.invia.setText(_translate("Iscrizione", "Invia"))
        self.label_5.setText(_translate("Iscrizione", "Cellulare"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Iscrizione = QtWidgets.QWidget()
    ui = Iscrizione()
    ui.setupUi(Iscrizione)
    Iscrizione.show()
    sys.exit(app.exec_())
