# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizzazione_liste.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_visualizzazioneliste(object):
    def setupUi(self, visualizzazioneliste):
        visualizzazioneliste.setObjectName("visualizzazioneliste")
        visualizzazioneliste.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(visualizzazioneliste)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listautenti = QtWidgets.QListView(visualizzazioneliste)
        self.listautenti.setGeometry(QtCore.QRect(25, 20, 341, 211))
        self.listautenti.setObjectName("listautenti")

        self.retranslateUi(visualizzazioneliste)
        self.buttonBox.accepted.connect(visualizzazioneliste.accept) # type: ignore
        self.buttonBox.rejected.connect(visualizzazioneliste.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(visualizzazioneliste)

    def retranslateUi(self, visualizzazioneliste):
        _translate = QtCore.QCoreApplication.translate
        visualizzazioneliste.setWindowTitle(_translate("visualizzazioneliste", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    visualizzazioneliste = QtWidgets.QDialog()
    ui = Ui_visualizzazioneliste()
    ui.setupUi(visualizzazioneliste)
    visualizzazioneliste.show()
    sys.exit(app.exec_())
