# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizzazione_liste.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from PyQt5.QtCore import QEvent,Qt

from Implementazione.Gestione.GestoreUtenti import GestoreUtenti



class Ui_visualizzazioneliste(object):




    def selezione(self):
        from Implementazione.Viste.registrazione_utente import UI_Iscrizione
        self.window_iscrizione = QtWidgets.QMainWindow()
        self.ui_iscrizione = UI_Iscrizione()
        self.ui_iscrizione.setupUi(self.window_iscrizione,self.tabellautenti.currentRow())
        self.window_iscrizione.show()
        self.tabellautenti.currentRow()

    def setupUi(self, visualizzazioneliste, visualizzasoci):
        visualizzazioneliste.setObjectName("visualizzazioneliste")
        visualizzazioneliste.resize(822, 334)
        self.buttonBox = QtWidgets.QDialogButtonBox(visualizzazioneliste)
        self.buttonBox.setGeometry(QtCore.QRect(340, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabellautenti = QtWidgets.QTableWidget(visualizzazioneliste)
        self.tabellautenti.setGeometry(QtCore.QRect(40, 10, 741, 251))
        self.tabellautenti.setObjectName("tabellautenti")
        self.tabellautenti.setColumnCount(7)
        self.tabellautenti.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tabellautenti.setHorizontalHeaderLabels(["Nome","Cognome","Data di nascita","Cellulare","Username","Password","Socio"])
        self.retranslateUi(visualizzazioneliste)
        self.buttonBox.accepted.connect(visualizzazioneliste.accept) # type: ignore
        self.buttonBox.rejected.connect(visualizzazioneliste.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(visualizzazioneliste)
        # griglia non modificabile
        self.tabellautenti.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        if(visualizzasoci==True):
            self.tabellautenti.setRowCount(GestoreUtenti.contaSoci)
            j = 0
            for i in range(len(GestoreUtenti.collectionUtenti) - 2):
                if GestoreUtenti.collectionUtenti[i].tesserato==True:
                    item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].nome)
                    self.tabellautenti.setItem(j, 0, item)
                    item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].cognome)
                    self.tabellautenti.setItem(j, 1, item)
                    item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].dataNascita)
                    self.tabellautenti.setItem(j, 2, item)
                    item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].cellulare)
                    self.tabellautenti.setItem(j, 3, item)
                    item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].nomeUtente)
                    self.tabellautenti.setItem(j, 4, item)
                    item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].password)
                    self.tabellautenti.setItem(j, 5, item)
                    item = QTableWidgetItem(str(GestoreUtenti.collectionUtenti[i].getTesseramento()))
                    self.tabellautenti.setItem(j, 6, item)
                    j+=1
        else:
            self.tabellautenti.setRowCount(len(GestoreUtenti.collectionUtenti) - 2)
            #sottraggo 2 che sono gli account in cima alla lista: admin e custode che non voglio si vedano
            for i in range(len(GestoreUtenti.collectionUtenti) - 2):
                item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].nome)
                self.tabellautenti.setItem(i, 0, item)
                item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].cognome)
                self.tabellautenti.setItem(i, 1, item)
                item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].dataNascita)
                self.tabellautenti.setItem(i, 2, item)
                item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].cellulare)
                self.tabellautenti.setItem(i, 3, item)
                item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].nomeUtente)
                self.tabellautenti.setItem(i, 4, item)
                item = QTableWidgetItem(GestoreUtenti.collectionUtenti[i].password)
                self.tabellautenti.setItem(i, 5, item)
                item = QTableWidgetItem(str(GestoreUtenti.collectionUtenti[i].getTesseramento()))
                self.tabellautenti.setItem(i, 6, item)

        self.tabellautenti.doubleClicked.connect(self.selezione)





    def retranslateUi(self, visualizzazioneliste):
        _translate = QtCore.QCoreApplication.translate
        visualizzazioneliste.setWindowTitle(_translate("visualizzazioneliste", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    visualizzazioneliste = QtWidgets.QDialog()
    ui = Ui_visualizzazioneliste()
    ui.setupUi(visualizzazioneliste)
    visualizzazioneliste.show()
    sys.exit(app.exec_())
